# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi3.yaml:
  no-unresolved-refs:
    - '#/paths/~1layers/post/requestBody/content/application~1json/schema/allOf/0'
    - '#/components/schemas/tocResponse/properties/metadata/oneOf/0'
  no-invalid-media-type-examples:
    - '#/paths/~1layers/post/requestBody/content/application~1json/schema'
bundledApi.yaml:
  no-invalid-media-type-examples:
    - '#/paths/~1layers/post/requestBody/content/application~1json/schema'
