{{- $chartName := include "discrete-overseer-creator.name" . -}}
{{- $tracingUrl := include "discrete-overseer-creator.tracingUrl" . -}}
{{- $metricsUrl := include "discrete-overseer-creator.metricsUrl" . -}}
{{- $tracingEnabled := include "discrete-overseer-creator.tracingEnabled" . -}}
{{- $metricsEnabled := include "discrete-overseer-creator.metricsEnabled" . -}}
{{- $metricsBuckets := include "discrete-overseer-creator.metricsBuckets" . -}}
{{- $configmapName := include "configmap.fullname" . }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $jobManagement := (include "common.jobManagement.merged" .) | fromYaml }}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $ingestion := (include "common.ingestion.merged" .) | fromYaml }}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName  }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  WATCH_DIRECTORY: {{ $ingestion.watchDirectoryOptions.directory | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  JOB_MANAGER_URL: {{ $serviceUrls.jobManager | quote }}
  SYNC_SERVICE_URL: {{ $serviceUrls.syncManager | quote }}
  MAP_PUBLISHING_SERVICE_URL: {{ $serviceUrls.mapproxyApi | quote }}
  PUBLIC_MAP_SERVER_URL: {{ $serviceUrls.mapServerPublicDNS | quote }}
  CATALOG_PUBLISHING_SERVICE_URL: {{ $serviceUrls.catalogManager | quote }}
  MAP_SERVER_CACHE_TYPE: {{ $storage.tilesStorageProvider | quote }}
  DISPLAY_NAME_DIR: {{ .Values.env.displayNameDir | quote }}
  VALID_FILE_EXTENSIONS: {{ .Values.env.validFileExtensions | toJson | quote }}
  TILING_ZOOM_GROUPS: {{ .Values.env.tilingZoomGroups | toJson | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.resetTimeout | quote }}
  DISABLE_HTTP_CLIENT_LOGS: {{ .Values.env.disableHttpClientLogs | quote }}
  LINK_TEMPLATE: {{ tpl (.Files.Get "config/linkTemplates.template") . | quote }}
  LAYER_SOURCE_DIR: {{ .Values.env.layerSourceDir | quote }}
  SHOULD_SYNC: {{ .Values.env.shouldSync | quote }}
  JOB_DOMAIN: {{ $jobManagement.jobDomain | quote }}
  INGESTION_NEW_JOB_TYPE: {{ $jobManagement.ingestion.new.jobType | quote }}
  INGESTION_SPLIT_TILES_TASK_TYPE: {{ $jobManagement.ingestion.new.splitTilesTaskType | quote }}
  INGESTION_UPDATE_JOB_TYPE: {{ $jobManagement.ingestion.update.jobType | quote }}
  INGESTION_MERGE_TASK_TYPE: {{ $jobManagement.ingestion.update.mergeTilesTaskType | quote }}
  INGESTION_SWAP_UPDATE_JOB_TYPE: {{ $jobManagement.ingestion.updateSwap.jobType | quote }}
  MAPPROXY_CACHE_GRIDS: {{ .Values.env.mapproxyCache.grids | quote }}
  SEED_JOB_TYPE: {{ $jobManagement.seed.jobType | quote }}
  SEED_TASK_TYPE: {{ $jobManagement.seed.taskType | quote }}
  SUPPORTED_INGESTION_SWAP_TYPES: {{ $jobManagement.ingestion.updateSwap.supportedIngestionSwapTypes | toJson | quote }}
  BBOX_SIZE_TILES: {{ .Values.env.bboxSizeTiles | quote }}
  MERGE_BATCH_SIZE: {{ .Values.env.mergeBatchSize | quote }}
  USE_NEW_TARGET_FLAG_IN_UPDATE_TASKS: {{ .Values.env.useNewTargetFlagInUpdateTasks | quote }}
  SPLITTER_TASKS_BATCH_SIZE: {{ .Values.env.splitterTasksBatchSize | quote }}
  MERGER_TASKS_BATCH_SIZE: {{ .Values.env.mergerTasksBatchSize | quote }}
  CRS: {{ .Values.env.validationValuesByInfo.crs | toJson | quote}}
  FILE_FORMAT: {{ .Values.env.validationValuesByInfo.fileFormat | toJson | quote}}
  PIXEL_SIZE_RANGE_MIN: {{ .Values.env.validationValuesByInfo.pixelSizeRange.min | quote}}
  PIXEL_SIZE_RANGE_MAX: {{ .Values.env.validationValuesByInfo.pixelSizeRange.max | quote}}
  TILE_SIZE: {{ .Values.env.validationValuesByInfo.tileSize | quote}}
  FORBIDDEN_TYPES_FOR_PARALLEL_INGESTION: {{ .Values.env.forbiddenTypesForParallelIngesion | toJson | quote }}
  TELEMETRY_TRACING_ENABLED: {{ $tracingEnabled | quote }}
  {{ if $tracingEnabled }}
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  TELEMETRY_METRICS_ENABLED: {{ $metricsEnabled | quote }}
  {{ if $metricsEnabled }}
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_BUCKETS: {{ $metricsBuckets | toJson | quote }}
  {{ end }}
{{- end }}
