{
 "title": "overseer",
 "tags": [
  "discrete-overseer-creator",
  "node.js"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(layer_creation_job_tasks_duration_seconds_count{namespace=\"$namespace\"},pod)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(layer_creation_job_tasks_duration_seconds_count,namespace)"
    }
   },
   {
    "name": "mergingBatchSize",
    "label": "mergingBatchSize",
    "query": {
     "query": "label_values(fill_batch_tasks_merging_duration_count,configurationBatchSize)"
    }
   },
   {
    "name": "splittingBatchSize",
    "label": "splittingBatchSize",
    "query": {
     "query": "label_values(fill_batch_tasks_splitter_duration_count,configurationBatchSize)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Jobs statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Total \"createLayer\"  creation status ",
   "type": "stat",
   "description": "The number of ingestion requests including New + Update ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(successCreatingJobTask) (layer_creation_job_tasks_duration_seconds_count{pod=\"$pod\",app=\"discrete-overseer-creator\"})"
    }
   ]
  },
  {
   "title": "Total \"createLayer\"  successed job creation by jobType (New\\Update)",
   "type": "stat",
   "description": "The number of ingestion requests including New + Update",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "create_layer_requests_total{pod=\"$pod\",app=\"discrete-overseer-creator\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Total jobs success creation by task type (splitting\\merging) since last restarts",
   "type": "stat",
   "description": "Total amount of Ingestion jobs that was created (including split\\merge, update\\new)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (taskType) (layer_creation_job_tasks_duration_seconds_count{pod=\"$pod\",app=\"discrete-overseer-creator\",successCreatingJobTask=\"true\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CreateLayer success job - tasks duration",
   "type": "timeseries",
   "description": "Time took to generate ingestion job + tasks into db (including New\\Update, Merging\\Splitting",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(layer_creation_job_tasks_duration_seconds_bucket{pod=\"$pod\",app=\"discrete-overseer-creator\",successCreatingJobTask=\"true\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(layer_creation_job_tasks_duration_seconds_bucket{pod=\"$pod\",app=\"discrete-overseer-creator\",successCreatingJobTask=\"true\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(rate(layer_creation_job_tasks_duration_seconds_sum{pod=\"$pod\",app=\"discrete-overseer-creator\",successCreatingJobTask=\"true\"}[$interval])) / sum(rate(layer_creation_job_tasks_duration_seconds_count{pod=\"$pod\",app=\"discrete-overseer-creator\",successCreatingJobTask=\"true\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TIme series fill batch for spliiting tasks (batch size of  $splittingBatchSize)",
   "type": "timeseries",
   "description": "Time took to fill single splitting tasks, based on configurable batch size.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(fill_batch_tasks_splitter_duration_bucket{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$splittingBatchSize\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(fill_batch_tasks_splitter_duration_bucket{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$splittingBatchSize\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(rate(fill_batch_tasks_splitter_duration_sum{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$splittingBatchSize\"}[$interval])) / sum(rate(fill_batch_tasks_splitter_duration_count{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$splittingBatchSize\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "TIme series fill batch for merging tasks (batch size of  $mergingBatchSize)",
   "type": "timeseries",
   "description": "Time took to fill single merging tasks, based on configurable batch size.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(fill_batch_tasks_merging_duration_bucket{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$mergingBatchSize\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(fill_batch_tasks_merging_duration_bucket{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$mergingBatchSize\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(rate(fill_batch_tasks_merging_duration_sum{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$mergingBatchSize\"}[$interval])) / sum(rate(fill_batch_tasks_merging_duration_count{pod=\"$pod\",app=\"discrete-overseer-creator\",configurationBatchSize=\"$mergingBatchSize\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  }
 ]
}